### ISSUE TITLE
拍照后跳转的界面是空白的

### ISSUE THREAD

**Issue by jxr202** [lvzhihao100/ORCamera#4]
拍照后跳转的界面是空白的，就是那个勾和X的界面，点击后啥也没有、
2019-07-30 17:37:19.259 27591-27723/com.jxr.tian V/Camera: sendStartPreviewBroadCast
2019-07-30 17:37:19.275 27591-27668/com.jxr.tian W/System.err: java.io.IOException: No such file or directory
2019-07-30 17:37:19.275 27591-27668/com.jxr.tian W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
2019-07-30 17:37:19.275 27591-27668/com.jxr.tian W/System.err:     at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)
2019-07-30 17:37:19.275 27591-27668/com.jxr.tian W/System.err:     at java.io.File.createNewFile(File.java:948)
2019-07-30 17:37:19.275 27591-27668/com.jxr.tian W/System.err:     at com.gamerole.orcameralib.CameraView.crop(CameraView.java:281)
2019-07-30 17:37:19.275 27591-27668/com.jxr.tian W/System.err:     at com.gamerole.orcameralib.CameraView.access$300(CameraView.java:32)
2019-07-30 17:37:19.275 27591-27668/com.jxr.tian W/System.err:     at com.gamerole.orcameralib.CameraView$CameraViewTakePictureCallback$1$1.run(CameraView.java:333)
2019-07-30 17:37:19.275 27591-27668/com.jxr.tian W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
2019-07-30 17:37:19.275 27591-27668/com.jxr.tian W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
2019-07-30 17:37:19.275 27591-27668/com.jxr.tian W/System.err:     at android.os.Looper.loop(Looper.java:154)
2019-07-30 17:37:19.275 27591-27668/com.jxr.tian W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by MyNameZyt** [comment]
啦啦啦
